# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VueTest CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      env:
            PRIVATE_KEY: ${{ secrets.KEY_EC2  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
         
#     - run: npm i
#       working-directory: vue
#     - run: npm run build 
#       working-directory: vue

    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.KEY_EC2 }}" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"
    # Build
#     - run: npm ci
#     - run: npm run build
#       working-directory: vue
     # Deploy
    - run: mkdir dist
    - run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . pepelsbey@pepelsbey.dev:/var/www/pepelsbey.dev/html/

      
#     - run: |
#           ssh -o StrictHostKeyChecking=no -i ${PRIVATE_KEY} ubuntu@ec2-3-131-36-182.us-east-2.compute.amazonaws.com
          


      
